;;-*- Mode: Lisp -*-

;; Copyright (C) 2021 Sam Halliday
;; License: GPL 3 or any later version

;;; Commentary:
;;
;;  See http://cask.readthedocs.org for information about Cask.
;;
;;; Code:

(source melpa-stable)

(package-file "ensime-mode.el")

;; Local Variables:
;; compile-command: "cask pkg-file && cask update && cask install"
;; End:

;;; Cask ends here
